name: project2-compose

services:
  controller:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: project2-image:latest
    container_name: controller
    hostname: controller
    command: ["python", "-u", "controller/controller.py"]
    ports:
      - "50050:50050"
    environment:
      PYTHONPATH: /app:/app/proto/src
    networks:
      - project2_net
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  storage-node-1:
    image: project2-image:latest
    container_name: storage-node-1
    hostname: storage-node-1
    command: ["python", "-u", "storage_node/node.py"]
    environment:
      GRPC_SERVER_PORT: "50051"
      NODE_TARGET: "storage-node-1:50051"
      PYTHONPATH: /app:/app/proto/src
    networks:
      - project2_net
    working_dir: /app

networks:
  project2_net:
    name: project2_net