
CONTROLLER_HOST = "host.docker.internal"
CONTROLLER_PORT = 50050
CONTROLLER_TARGET = f"{CONTROLLER_HOST}:{CONTROLLER_PORT}"

NODE_PORT = 50051
DOCKER_IMAGE = "project2-image:latest"
DOCKER_NETWORK = "project2_net"
