# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import project2_pb2 as project2__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in project2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/project2.ControllerService/Put',
                request_serializer=project2__pb2.PutRequest.SerializeToString,
                response_deserializer=project2__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/project2.ControllerService/Search',
                request_serializer=project2__pb2.SearchRequest.SerializeToString,
                response_deserializer=project2__pb2.SearchLocalResponse.FromString,
                _registered_method=True)
        self.ClusterStatus = channel.unary_unary(
                '/project2.ControllerService/ClusterStatus',
                request_serializer=project2__pb2.ClusterStatusRequest.SerializeToString,
                response_deserializer=project2__pb2.ClusterStatusResponse.FromString,
                _registered_method=True)


class ControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClusterStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=project2__pb2.PutRequest.FromString,
                    response_serializer=project2__pb2.PutResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=project2__pb2.SearchRequest.FromString,
                    response_serializer=project2__pb2.SearchLocalResponse.SerializeToString,
            ),
            'ClusterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ClusterStatus,
                    request_deserializer=project2__pb2.ClusterStatusRequest.FromString,
                    response_serializer=project2__pb2.ClusterStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project2.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project2.ControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project2.ControllerService/Put',
            project2__pb2.PutRequest.SerializeToString,
            project2__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project2.ControllerService/Search',
            project2__pb2.SearchRequest.SerializeToString,
            project2__pb2.SearchLocalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClusterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project2.ControllerService/ClusterStatus',
            project2__pb2.ClusterStatusRequest.SerializeToString,
            project2__pb2.ClusterStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StorageNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreRecord = channel.unary_unary(
                '/project2.StorageNodeService/StoreRecord',
                request_serializer=project2__pb2.StoreRecordRequest.SerializeToString,
                response_deserializer=project2__pb2.StoreRecordResponse.FromString,
                _registered_method=True)
        self.SearchLocal = channel.unary_unary(
                '/project2.StorageNodeService/SearchLocal',
                request_serializer=project2__pb2.SearchLocalRequest.SerializeToString,
                response_deserializer=project2__pb2.SearchLocalResponse.FromString,
                _registered_method=True)
        self.ReplaceLocalPartition = channel.unary_unary(
                '/project2.StorageNodeService/ReplaceLocalPartition',
                request_serializer=project2__pb2.ReplaceLocalPartitionRequest.SerializeToString,
                response_deserializer=project2__pb2.ReplaceLocalPartitionResponse.FromString,
                _registered_method=True)
        self.SplitPartition = channel.unary_unary(
                '/project2.StorageNodeService/SplitPartition',
                request_serializer=project2__pb2.SplitPartitionRequest.SerializeToString,
                response_deserializer=project2__pb2.SplitPartitionResponse.FromString,
                _registered_method=True)
        self.GetNodeStats = channel.unary_unary(
                '/project2.StorageNodeService/GetNodeStats',
                request_serializer=project2__pb2.GetNodeStatsRequest.SerializeToString,
                response_deserializer=project2__pb2.NodeStats.FromString,
                _registered_method=True)


class StorageNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchLocal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceLocalPartition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SplitPartition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreRecord,
                    request_deserializer=project2__pb2.StoreRecordRequest.FromString,
                    response_serializer=project2__pb2.StoreRecordResponse.SerializeToString,
            ),
            'SearchLocal': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchLocal,
                    request_deserializer=project2__pb2.SearchLocalRequest.FromString,
                    response_serializer=project2__pb2.SearchLocalResponse.SerializeToString,
            ),
            'ReplaceLocalPartition': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceLocalPartition,
                    request_deserializer=project2__pb2.ReplaceLocalPartitionRequest.FromString,
                    response_serializer=project2__pb2.ReplaceLocalPartitionResponse.SerializeToString,
            ),
            'SplitPartition': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitPartition,
                    request_deserializer=project2__pb2.SplitPartitionRequest.FromString,
                    response_serializer=project2__pb2.SplitPartitionResponse.SerializeToString,
            ),
            'GetNodeStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeStats,
                    request_deserializer=project2__pb2.GetNodeStatsRequest.FromString,
                    response_serializer=project2__pb2.NodeStats.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project2.StorageNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project2.StorageNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project2.StorageNodeService/StoreRecord',
            project2__pb2.StoreRecordRequest.SerializeToString,
            project2__pb2.StoreRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchLocal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project2.StorageNodeService/SearchLocal',
            project2__pb2.SearchLocalRequest.SerializeToString,
            project2__pb2.SearchLocalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceLocalPartition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project2.StorageNodeService/ReplaceLocalPartition',
            project2__pb2.ReplaceLocalPartitionRequest.SerializeToString,
            project2__pb2.ReplaceLocalPartitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SplitPartition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project2.StorageNodeService/SplitPartition',
            project2__pb2.SplitPartitionRequest.SerializeToString,
            project2__pb2.SplitPartitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project2.StorageNodeService/GetNodeStats',
            project2__pb2.GetNodeStatsRequest.SerializeToString,
            project2__pb2.NodeStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
